name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@vinhvizg1040'
      - run: npm ci
      - run: npm run build --if-present
      #- run: npm publish --provenance --access public
      - run: npm test
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
